version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fact
    volumes:
      - ./:/fact
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1